skillMetadata:
  sections:
    - name: Credentials
      fields:
        - name: username
          type: text
          label: Username of the host
          value: "root"
        - name: password
          type: password
          label: password of the device to ssh into. On kodi it is by default libreelec
          value: "libreelec"
        - name: hostname
          type: text
          label: the name after the @ in the terminal of the host
          value: "10.0.0.154"
        - name: devicename
          type: text
          label: device name
          value: /dev/ttyUSB0
